### ISSUE TITLE
Maj Routes 

### ISSUE THREAD

**Issue by alyssaMel** [marouanemouloue/pizzeriaAPP#1]
// Il manque la ligne de redirection quand le path est vide, 
// il redirige vers pizza et quand c'est n"importe quoi, on redirige vers la page not found 
  {path:'',redirectTo: 'pizzas',pathMatch: 'full'},
  {path:'**',component: PageNotFoundComponent}

**Comment by alyssaMel** [comment]
Il manque la ligne de redirection quand le path est vide, il redirige vers pizza et quand c'est n"importe quoi, on redirige vers la page not found

**Comment by marouanemouloue** [comment]
Effectivement, je l'ai ajouté dans le nouveau commit.
